FROM registry.redhat.io/ubi7/go-toolset
LABEL maintainer="Radomir Ludva"

EXPOSE 8080
	
RUN git clone https://github.com/rludva/sputnik.git && \
    export GOPATH=/opt/app-root/src/sputnik && \
    cd /opt/app-root/src/sputnik/src && go build -o ../sputnik

ENTRYPOINT /opt/app-root/src/sputnik/sputnik
