FROM registry.redhat.io/ubi7/go-toolset
LABEL maintainer="Radomir Ludva"

EXPOSE 8080
	
RUN git clone https://github.com/rludva/sputnik.git && \
		cd /opt/app-root/src/sputnik && \
		go build sputnik.go

ENTRYPOINT /opt/app-root/src/sputnik/sputnik
